# CMake generated Testfile for 
# Source directory: /home/hh/searchEngine/test
# Build directory: /home/hh/searchEngine/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cache_test "/home/hh/searchEngine/test/cache_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/cache_test.xml")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(configuration_test "/home/hh/searchEngine/test/configuration_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/configuration_test.xml")
set_tests_properties(configuration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(split_tool_test "/home/hh/searchEngine/test/split_tool_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/split_tool_test.xml")
set_tests_properties(split_tool_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(jieba_test "/home/hh/searchEngine/test/jieba_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/jieba_test.xml")
set_tests_properties(jieba_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(conf_test "/home/hh/searchEngine/test/conf_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/conf_test.xml")
set_tests_properties(conf_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(dict_test "/home/hh/searchEngine/test/dict_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/dict_test.xml")
set_tests_properties(dict_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(key_test "/home/hh/searchEngine/test/key_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/key_test.xml")
set_tests_properties(key_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(simhash_test "/home/hh/searchEngine/test/simhash_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/simhash_test.xml")
set_tests_properties(simhash_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(page_lib_preprocessor_test "/home/hh/searchEngine/test/page_lib_preprocessor_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/page_lib_preprocessor_test.xml")
set_tests_properties(page_lib_preprocessor_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(page_lib_test "/home/hh/searchEngine/test/page_lib_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/page_lib_test.xml")
set_tests_properties(page_lib_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(rss_parser_test "/home/hh/searchEngine/test/rss_parser_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/rss_parser_test.xml")
set_tests_properties(rss_parser_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(web_page2_test "/home/hh/searchEngine/test/web_page2_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/web_page2_test.xml")
set_tests_properties(web_page2_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(web_page_query2_test "/home/hh/searchEngine/test/web_page_query2_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/web_page_query2_test.xml")
set_tests_properties(web_page_query2_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(web_page_query_test "/home/hh/searchEngine/test/web_page_query_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/web_page_query_test.xml")
set_tests_properties(web_page_query_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
add_test(web_page_test "/home/hh/searchEngine/test/web_page_test" "--gtest_color=yes" "--gtest_output=xml:/home/hh/searchEngine/test/web_page_test.xml")
set_tests_properties(web_page_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hh/searchEngine/test/CMakeLists.txt;104;add_test;/home/hh/searchEngine/test/CMakeLists.txt;0;")
